### ISSUE TITLE
Issue Downloading Pretrained Weights - Broken Link

### ISSUE THREAD

**Issue by maiabourobea** [TUMFTM/CamRaDepth#10]
Hello CamRaDepth Team,

I hope this message finds you well.

I have been attempting to download the pretrained weights as per the instructions provided in the repository. However, the link appears to be broken, resulting in a 404 error. Here is the specific command and URL I used:

wget https://syncandshare.lrz.de/dl/fi17pZyWBpZf38uxQ5XcS3/checkpoints.zip
Upon running this command, I receive the following error message:

HTTP request sent, awaiting response... 404 Not Found
2024-11-13 11:38:12 ERROR 404: Not Found.

It seems that the file might be moved, renamed, or removed from the server. Could you kindly confirm the current location of the pretrained weights or provide an updated link if available?

Thank you for your assistance. I look forward to your guidance.

Best regards,
Mai Abourobea

**Comment by never-to-never** [comment]
I have encountered the same problem, could the author please solve it?

**Comment by never-to-never** [comment]
@Skrsch

**Comment by Skrsch** [comment]
Hey guys,
sorry for the late reply. I created a new link and uploaded the pretrained weights.
Find documentation in the Readme. Please let me know if this works, so I can close this issue.

Cheers!

**Comment by never-to-never** [comment]
> Hey guys, sorry for the late reply. I created a new link and uploaded the pretrained weights. Find documentation in the Readme. Please let me know if this works, so I can close this issue.
> 
> Cheers!

It is now available for download. Thank you very much！
